# Generated by Django 6.0.5 on 2026-05-20 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='guards/profiles/')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('description', models.TextField(blank=True)),
                ('guard_tag', models.CharField(blank=True, max_length=100)),
                ('digital_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='guards/id_cards/')),
                ('gate_registered_on', models.CharField(blank=True, max_length=50)),
                ('gates_assigned_to', models.CharField(blank=True, max_length=255)),
                ('registered_by', models.CharField(blank=True, max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('gate_camera_id', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guard_profile',
            },
        ),
    ]
