# Generated by Django 6.0.5 on 2026-05-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GateWithCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_name', models.CharField(max_length=100)),
                ('camera_name', models.CharField(max_length=100)),
                ('terminal_id', models.CharField(max_length=50, unique=True)),
                ('power', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'On Maintenance')], default='active', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cameras_gate',
                'ordering': ['-created_at'],
            },
        ),
    ]
