# Generated by Django 6.0.5 on 2026-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_expiry_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
