# Generated by Django 6.0.5 on 2026-06-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitor_is_approved_visitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrequest',
            name='guard_image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
