# Generated by Django 6.0.5 on 2026-05-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_image', models.CharField(blank=True, max_length=512)),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SCAN_ACCEPTED', 'Scan Accepted'), ('SCAN_REJECTED', 'Scan Rejected'), ('SPOOF_DETECTED', 'Spoof Detected'), ('ATTEMPT_LIMIT', 'Attempt Limit Reached'), ('REGISTER', 'User Registered'), ('EDIT', 'User Edited'), ('DELETE', 'User Deleted'), ('REQUEST_SUBMIT', 'Request Submitted'), ('REQUEST_APPROVE', 'Request Approved'), ('REQUEST_DENY', 'Request Denied'), ('CAMERA_ADD', 'Camera Added'), ('CAMERA_EDIT', 'Camera Edited'), ('CAMERA_POWER', 'Camera Power Toggle'), ('SYSTEM', 'System Event')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('gate_camera_id', models.CharField(blank=True, max_length=50)),
                ('ethiopian_time', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('scan_result', models.CharField(blank=True, max_length=30)),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_actor', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'access_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
