# Generated by Django 6.0.5 on 2026-05-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff/profiles/')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('staff_tag', models.CharField(blank=True, max_length=100)),
                ('digital_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='staff/id_cards/')),
                ('gate_registered_on', models.CharField(blank=True, max_length=50)),
                ('registered_by', models.CharField(blank=True, max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_profile',
            },
        ),
    ]
