# Generated by Django 6.0.5 on 2026-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='privileges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
