# Generated by Django 6.0.5 on 2026-05-26 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_adminprofile_is_super_admin_adminprofile_privileges'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='linked_staff',
            field=models.OneToOneField(blank=True, help_text='If this admin is also a staff member, link their StaffProfile here so face recognition shows the Admin identity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_override', to='staff.staffprofile'),
        ),
    ]
