# Generated by Django 6.0.5 on 2026-05-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('face_front', models.ImageField(blank=True, null=True, upload_to='biometrics/faces/')),
                ('face_left', models.ImageField(blank=True, null=True, upload_to='biometrics/faces/')),
                ('face_right', models.ImageField(blank=True, null=True, upload_to='biometrics/faces/')),
                ('face_down', models.ImageField(blank=True, null=True, upload_to='biometrics/faces/')),
                ('face_unusual', models.ImageField(blank=True, null=True, upload_to='biometrics/faces/')),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='biometrics/ids/')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='biometrics/ids/')),
                ('face_encodings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'recognition_biometric',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='recognition_content_0d4ef7_idx')],
            },
        ),
    ]
